### ISSUE TITLE
Dependency on magit-popup

### ISSUE THREAD

**Issue by mgttlinger** [Ailrun/magit-lfs#1]
`magit-lfs` depends on `magit-define-pupup` which got moved to the library `magit-popup` which `magit-lfs` should hence depend on.

**Comment by Ailrun** [comment]
@mgttlinger Thank you for your reporting! I fixed it. Could you check whether it works with your environment?
c.f. @declanqian

**Comment by mgttlinger** [comment]
Sorry for the late reply. Yes this fixed it. Thanks for your work!
